# Probability {#sec-probability-bg-ch}

I assume that you have seen
some probability theory before, and that this is just a reminder.
If you need a more thorough refresher, the book by Ross [@ross-2014]
is a
popular introductory text that covers discrete and continuous
problems, but not more general probability measures. Another good
undergraduate text by Chung and AitSahlia [@chung-aitsahlia-2003]
includes a little bit of measure theory.  Good graduate texts include
the books by Billingsley [@billingsley-1995] and by Breiman [@breiman-1992].
If you want a reminder that is more thorough than
the one we give here, but less than a full textbook, the treatment in
[@deisenroth-faisal-ong-2020] is a good starting point.

- Axiomatic probability, counting, and measure
- Conditional and marginal probabilities
- Bayesian and frequentist perspectives

- Random variables
- The wonder of Gaussians (and not all RVs are Gaussian!)

- Moments (+ linearity of expectations, variance and precision,heteroscedasticity, etc) and tails
- Independence, conditional independence, factorization of probabilities, graphical models

- Standard statistics (incl variance and precision)
- Central limit theorem / LLN / sums

- Parameter estimation

- Bayes and updating
- Conjugate priors
- Uninformative priors

- Markov chains
- Martingales
- Stochastic processes

- Standard inequalities and concentration of measure
